/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "fsm.v:1" *)
 module synth_fsm(clk, reset, init, main_fifo_low, main_fifo_high, Vco_low, Vco_high, Vc1_low, Vc1_high, Do_low, Do_high, D1_low, D1_high, empties, errors, synth_error_out, synth_active_out, synth_idle_out, synth_mf_l, synth_mf_h, synth_vco_l, synth_vco_h, synth_vc1_l, synth_vc1_h, synth_do_l, synth_do_h, synth_d1_l, synth_d1_h);
  (* src = "fsm.v:46" *)
  wire [4:0] _000_;
  (* src = "fsm.v:46" *)
  wire [4:0] _001_;
  (* src = "fsm.v:46" *)
  wire [4:0] _002_;
  (* src = "fsm.v:46" *)
  wire [4:0] _003_;
  (* src = "fsm.v:46" *)
  wire [4:0] _004_;
  (* src = "fsm.v:46" *)
  wire [4:0] _005_;
  (* src = "fsm.v:46" *)
  wire [4:0] _006_;
  (* src = "fsm.v:46" *)
  wire [4:0] _007_;
  (* src = "fsm.v:46" *)
  wire [4:0] _008_;
  (* src = "fsm.v:46" *)
  wire [4:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  (* src = "fsm.v:14" *)
  input [4:0] D1_high;
  (* src = "fsm.v:13" *)
  input [4:0] D1_low;
  (* src = "fsm.v:12" *)
  input [4:0] Do_high;
  (* src = "fsm.v:11" *)
  input [4:0] Do_low;
  (* src = "fsm.v:10" *)
  input [4:0] Vc1_high;
  (* src = "fsm.v:9" *)
  input [4:0] Vc1_low;
  (* src = "fsm.v:8" *)
  input [4:0] Vco_high;
  (* src = "fsm.v:7" *)
  input [4:0] Vco_low;
  (* src = "fsm.v:18" *)
  output synth_active_out;
  (* src = "fsm.v:2" *)
  input clk;
  (* src = "fsm.v:29" *)
  output [4:0] synth_d1_h;
  (* src = "fsm.v:28" *)
  output [4:0] synth_d1_l;
  (* src = "fsm.v:27" *)
  output [4:0] synth_do_h;
  (* src = "fsm.v:26" *)
  output [4:0] synth_do_l;
  (* src = "fsm.v:15" *)
  input [4:0] empties;
  (* src = "fsm.v:17" *)
  output synth_error_out;
  (* src = "fsm.v:16" *)
  input [4:0] errors;
  (* src = "fsm.v:19" *)
  output synth_idle_out;
  (* src = "fsm.v:4" *)
  input init;
  (* src = "fsm.v:6" *)
  input [4:0] main_fifo_high;
  (* src = "fsm.v:5" *)
  input [4:0] main_fifo_low;
  (* src = "fsm.v:21" *)
  output [4:0] synth_mf_h;
  (* src = "fsm.v:20" *)
  output [4:0] synth_mf_l;
  (* src = "fsm.v:3" *)
  input reset;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  (* src = "fsm.v:25" *)
  output [4:0] synth_vc1_h;
  (* src = "fsm.v:24" *)
  output [4:0] synth_vc1_l;
  (* src = "fsm.v:23" *)
  output [4:0] synth_vco_h;
  (* src = "fsm.v:22" *)
  output [4:0] synth_vco_l;
  NOR _157_ (
    .A(empties[4]),
    .B(empties[2]),
    .Y(_010_)
  );
  NOT _158_ (
    .A(empties[0]),
    .Y(_011_)
  );
  NOT _159_ (
    .A(empties[1]),
    .Y(_012_)
  );
  NAND _160_ (
    .A(_012_),
    .B(_011_),
    .Y(_013_)
  );
  NOR _161_ (
    .A(_013_),
    .B(empties[3]),
    .Y(_015_)
  );
  NAND _162_ (
    .A(_015_),
    .B(_010_),
    .Y(_016_)
  );
  NOT _163_ (
    .A(state[3]),
    .Y(_017_)
  );
  NOT _164_ (
    .A(init),
    .Y(_018_)
  );
  NAND _165_ (
    .A(reset),
    .B(_018_),
    .Y(_019_)
  );
  NOR _166_ (
    .A(_019_),
    .B(_017_),
    .Y(_020_)
  );
  NAND _167_ (
    .A(_020_),
    .B(_016_),
    .Y(_021_)
  );
  NOT _168_ (
    .A(errors[0]),
    .Y(_022_)
  );
  NOT _169_ (
    .A(errors[1]),
    .Y(_023_)
  );
  NAND _170_ (
    .A(_023_),
    .B(_022_),
    .Y(_024_)
  );
  NOT _171_ (
    .A(errors[4]),
    .Y(_025_)
  );
  NOR _172_ (
    .A(errors[3]),
    .B(errors[2]),
    .Y(_026_)
  );
  NAND _173_ (
    .A(_026_),
    .B(_025_),
    .Y(_027_)
  );
  NOR _174_ (
    .A(_027_),
    .B(_024_),
    .Y(_028_)
  );
  NOT _175_ (
    .A(state[2]),
    .Y(_029_)
  );
  NOR _176_ (
    .A(_019_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _177_ (
    .A(_030_),
    .B(_028_),
    .Y(_031_)
  );
  NAND _178_ (
    .A(_031_),
    .B(_021_),
    .Y(_156_)
  );
  NOT _179_ (
    .A(state[4]),
    .Y(_032_)
  );
  NOT _180_ (
    .A(state[0]),
    .Y(_033_)
  );
  NAND _181_ (
    .A(_033_),
    .B(_032_),
    .Y(_034_)
  );
  NAND _182_ (
    .A(_029_),
    .B(_017_),
    .Y(_035_)
  );
  NOR _183_ (
    .A(_035_),
    .B(_034_),
    .Y(_036_)
  );
  NAND _184_ (
    .A(_033_),
    .B(_018_),
    .Y(_037_)
  );
  NAND _185_ (
    .A(_037_),
    .B(reset),
    .Y(_038_)
  );
  NOR _186_ (
    .A(_038_),
    .B(_036_),
    .Y(_014_)
  );
  NOT _187_ (
    .A(empties[4]),
    .Y(_039_)
  );
  NOR _188_ (
    .A(empties[3]),
    .B(empties[2]),
    .Y(_040_)
  );
  NAND _189_ (
    .A(_040_),
    .B(_039_),
    .Y(_041_)
  );
  NOR _190_ (
    .A(_041_),
    .B(_013_),
    .Y(_042_)
  );
  NAND _191_ (
    .A(_020_),
    .B(_042_),
    .Y(_043_)
  );
  NOT _192_ (
    .A(_019_),
    .Y(_044_)
  );
  NAND _193_ (
    .A(_044_),
    .B(state[4]),
    .Y(_045_)
  );
  NAND _194_ (
    .A(_045_),
    .B(_043_),
    .Y(_095_)
  );
  NOT _195_ (
    .A(_043_),
    .Y(synth_idle_out)
  );
  NOT _196_ (
    .A(_031_),
    .Y(synth_active_out)
  );
  NAND _197_ (
    .A(state[1]),
    .B(reset),
    .Y(_046_)
  );
  NOT _198_ (
    .A(_046_),
    .Y(synth_error_out)
  );
  NAND _199_ (
    .A(_034_),
    .B(reset),
    .Y(_047_)
  );
  NAND _200_ (
    .A(_047_),
    .B(synth_mf_l[0]),
    .Y(_048_)
  );
  NOT _201_ (
    .A(reset),
    .Y(_120_)
  );
  NOR _202_ (
    .A(_120_),
    .B(_032_),
    .Y(_049_)
  );
  NAND _203_ (
    .A(_049_),
    .B(main_fifo_low[0]),
    .Y(_050_)
  );
  NAND _204_ (
    .A(_050_),
    .B(_048_),
    .Y(_005_[0])
  );
  NAND _205_ (
    .A(_047_),
    .B(synth_mf_l[1]),
    .Y(_051_)
  );
  NAND _206_ (
    .A(_049_),
    .B(main_fifo_low[1]),
    .Y(_052_)
  );
  NAND _207_ (
    .A(_052_),
    .B(_051_),
    .Y(_005_[1])
  );
  NAND _208_ (
    .A(_047_),
    .B(synth_mf_l[2]),
    .Y(_053_)
  );
  NAND _209_ (
    .A(_049_),
    .B(main_fifo_low[2]),
    .Y(_054_)
  );
  NAND _210_ (
    .A(_054_),
    .B(_053_),
    .Y(_005_[2])
  );
  NAND _211_ (
    .A(_047_),
    .B(synth_mf_l[3]),
    .Y(_055_)
  );
  NAND _212_ (
    .A(_049_),
    .B(main_fifo_low[3]),
    .Y(_056_)
  );
  NAND _213_ (
    .A(_056_),
    .B(_055_),
    .Y(_005_[3])
  );
  NAND _214_ (
    .A(_047_),
    .B(synth_mf_l[4]),
    .Y(_057_)
  );
  NAND _215_ (
    .A(_049_),
    .B(main_fifo_low[4]),
    .Y(_058_)
  );
  NAND _216_ (
    .A(_058_),
    .B(_057_),
    .Y(_005_[4])
  );
  NAND _217_ (
    .A(_047_),
    .B(synth_d1_h[0]),
    .Y(_059_)
  );
  NAND _218_ (
    .A(_049_),
    .B(D1_high[0]),
    .Y(_060_)
  );
  NAND _219_ (
    .A(_060_),
    .B(_059_),
    .Y(_000_[0])
  );
  NAND _220_ (
    .A(_047_),
    .B(synth_d1_h[1]),
    .Y(_061_)
  );
  NAND _221_ (
    .A(_049_),
    .B(D1_high[1]),
    .Y(_062_)
  );
  NAND _222_ (
    .A(_062_),
    .B(_061_),
    .Y(_000_[1])
  );
  NAND _223_ (
    .A(_047_),
    .B(synth_d1_h[2]),
    .Y(_063_)
  );
  NAND _224_ (
    .A(_049_),
    .B(D1_high[2]),
    .Y(_064_)
  );
  NAND _225_ (
    .A(_064_),
    .B(_063_),
    .Y(_000_[2])
  );
  NAND _226_ (
    .A(_047_),
    .B(synth_d1_h[3]),
    .Y(_065_)
  );
  NAND _227_ (
    .A(_049_),
    .B(D1_high[3]),
    .Y(_066_)
  );
  NAND _228_ (
    .A(_066_),
    .B(_065_),
    .Y(_000_[3])
  );
  NAND _229_ (
    .A(_047_),
    .B(synth_d1_h[4]),
    .Y(_067_)
  );
  NAND _230_ (
    .A(_049_),
    .B(D1_high[4]),
    .Y(_068_)
  );
  NAND _231_ (
    .A(_068_),
    .B(_067_),
    .Y(_000_[4])
  );
  NAND _232_ (
    .A(_047_),
    .B(synth_d1_l[0]),
    .Y(_069_)
  );
  NAND _233_ (
    .A(_049_),
    .B(D1_low[0]),
    .Y(_070_)
  );
  NAND _234_ (
    .A(_070_),
    .B(_069_),
    .Y(_001_[0])
  );
  NAND _235_ (
    .A(_047_),
    .B(synth_d1_l[1]),
    .Y(_071_)
  );
  NAND _236_ (
    .A(_049_),
    .B(D1_low[1]),
    .Y(_072_)
  );
  NAND _237_ (
    .A(_072_),
    .B(_071_),
    .Y(_001_[1])
  );
  NAND _238_ (
    .A(_047_),
    .B(synth_d1_l[2]),
    .Y(_073_)
  );
  NAND _239_ (
    .A(_049_),
    .B(D1_low[2]),
    .Y(_074_)
  );
  NAND _240_ (
    .A(_074_),
    .B(_073_),
    .Y(_001_[2])
  );
  NAND _241_ (
    .A(_047_),
    .B(synth_d1_l[3]),
    .Y(_075_)
  );
  NAND _242_ (
    .A(_049_),
    .B(D1_low[3]),
    .Y(_076_)
  );
  NAND _243_ (
    .A(_076_),
    .B(_075_),
    .Y(_001_[3])
  );
  NAND _244_ (
    .A(_047_),
    .B(synth_d1_l[4]),
    .Y(_077_)
  );
  NAND _245_ (
    .A(_049_),
    .B(D1_low[4]),
    .Y(_078_)
  );
  NAND _246_ (
    .A(_078_),
    .B(_077_),
    .Y(_001_[4])
  );
  NAND _247_ (
    .A(_047_),
    .B(synth_do_h[0]),
    .Y(_079_)
  );
  NAND _248_ (
    .A(_049_),
    .B(Do_high[0]),
    .Y(_080_)
  );
  NAND _249_ (
    .A(_080_),
    .B(_079_),
    .Y(_002_[0])
  );
  NAND _250_ (
    .A(_047_),
    .B(synth_do_h[1]),
    .Y(_081_)
  );
  NAND _251_ (
    .A(_049_),
    .B(Do_high[1]),
    .Y(_082_)
  );
  NAND _252_ (
    .A(_082_),
    .B(_081_),
    .Y(_002_[1])
  );
  NAND _253_ (
    .A(_047_),
    .B(synth_do_h[2]),
    .Y(_083_)
  );
  NAND _254_ (
    .A(_049_),
    .B(Do_high[2]),
    .Y(_084_)
  );
  NAND _255_ (
    .A(_084_),
    .B(_083_),
    .Y(_002_[2])
  );
  NAND _256_ (
    .A(_047_),
    .B(synth_do_h[3]),
    .Y(_085_)
  );
  NAND _257_ (
    .A(_049_),
    .B(Do_high[3]),
    .Y(_086_)
  );
  NAND _258_ (
    .A(_086_),
    .B(_085_),
    .Y(_002_[3])
  );
  NAND _259_ (
    .A(_047_),
    .B(synth_do_h[4]),
    .Y(_087_)
  );
  NAND _260_ (
    .A(_049_),
    .B(Do_high[4]),
    .Y(_088_)
  );
  NAND _261_ (
    .A(_088_),
    .B(_087_),
    .Y(_002_[4])
  );
  NAND _262_ (
    .A(_047_),
    .B(synth_do_l[0]),
    .Y(_089_)
  );
  NAND _263_ (
    .A(_049_),
    .B(Do_low[0]),
    .Y(_090_)
  );
  NAND _264_ (
    .A(_090_),
    .B(_089_),
    .Y(_003_[0])
  );
  NAND _265_ (
    .A(_047_),
    .B(synth_do_l[1]),
    .Y(_091_)
  );
  NAND _266_ (
    .A(_049_),
    .B(Do_low[1]),
    .Y(_092_)
  );
  NAND _267_ (
    .A(_092_),
    .B(_091_),
    .Y(_003_[1])
  );
  NAND _268_ (
    .A(_047_),
    .B(synth_do_l[2]),
    .Y(_093_)
  );
  NAND _269_ (
    .A(_049_),
    .B(Do_low[2]),
    .Y(_094_)
  );
  NAND _270_ (
    .A(_094_),
    .B(_093_),
    .Y(_003_[2])
  );
  NAND _271_ (
    .A(_047_),
    .B(synth_do_l[3]),
    .Y(_096_)
  );
  NAND _272_ (
    .A(_049_),
    .B(Do_low[3]),
    .Y(_097_)
  );
  NAND _273_ (
    .A(_097_),
    .B(_096_),
    .Y(_003_[3])
  );
  NAND _274_ (
    .A(_047_),
    .B(synth_do_l[4]),
    .Y(_098_)
  );
  NAND _275_ (
    .A(_049_),
    .B(Do_low[4]),
    .Y(_099_)
  );
  NAND _276_ (
    .A(_099_),
    .B(_098_),
    .Y(_003_[4])
  );
  NAND _277_ (
    .A(_047_),
    .B(synth_vc1_h[0]),
    .Y(_100_)
  );
  NAND _278_ (
    .A(_049_),
    .B(Vc1_high[0]),
    .Y(_101_)
  );
  NAND _279_ (
    .A(_101_),
    .B(_100_),
    .Y(_006_[0])
  );
  NAND _280_ (
    .A(_047_),
    .B(synth_vc1_h[1]),
    .Y(_102_)
  );
  NAND _281_ (
    .A(_049_),
    .B(Vc1_high[1]),
    .Y(_103_)
  );
  NAND _282_ (
    .A(_103_),
    .B(_102_),
    .Y(_006_[1])
  );
  NAND _283_ (
    .A(_047_),
    .B(synth_vc1_h[2]),
    .Y(_104_)
  );
  NAND _284_ (
    .A(_049_),
    .B(Vc1_high[2]),
    .Y(_105_)
  );
  NAND _285_ (
    .A(_105_),
    .B(_104_),
    .Y(_006_[2])
  );
  NAND _286_ (
    .A(_047_),
    .B(synth_vc1_h[3]),
    .Y(_106_)
  );
  NAND _287_ (
    .A(_049_),
    .B(Vc1_high[3]),
    .Y(_107_)
  );
  NAND _288_ (
    .A(_107_),
    .B(_106_),
    .Y(_006_[3])
  );
  NAND _289_ (
    .A(_047_),
    .B(synth_vc1_h[4]),
    .Y(_108_)
  );
  NAND _290_ (
    .A(_049_),
    .B(Vc1_high[4]),
    .Y(_109_)
  );
  NAND _291_ (
    .A(_109_),
    .B(_108_),
    .Y(_006_[4])
  );
  NAND _292_ (
    .A(_047_),
    .B(synth_vc1_l[0]),
    .Y(_110_)
  );
  NAND _293_ (
    .A(_049_),
    .B(Vc1_low[0]),
    .Y(_111_)
  );
  NAND _294_ (
    .A(_111_),
    .B(_110_),
    .Y(_007_[0])
  );
  NAND _295_ (
    .A(_047_),
    .B(synth_vc1_l[1]),
    .Y(_112_)
  );
  NAND _296_ (
    .A(_049_),
    .B(Vc1_low[1]),
    .Y(_113_)
  );
  NAND _297_ (
    .A(_113_),
    .B(_112_),
    .Y(_007_[1])
  );
  NAND _298_ (
    .A(_047_),
    .B(synth_vc1_l[2]),
    .Y(_114_)
  );
  NAND _299_ (
    .A(_049_),
    .B(Vc1_low[2]),
    .Y(_115_)
  );
  NAND _300_ (
    .A(_115_),
    .B(_114_),
    .Y(_007_[2])
  );
  NAND _301_ (
    .A(_047_),
    .B(synth_vc1_l[3]),
    .Y(_116_)
  );
  NAND _302_ (
    .A(_049_),
    .B(Vc1_low[3]),
    .Y(_117_)
  );
  NAND _303_ (
    .A(_117_),
    .B(_116_),
    .Y(_007_[3])
  );
  NAND _304_ (
    .A(_047_),
    .B(synth_vc1_l[4]),
    .Y(_118_)
  );
  NAND _305_ (
    .A(_049_),
    .B(Vc1_low[4]),
    .Y(_119_)
  );
  NAND _306_ (
    .A(_119_),
    .B(_118_),
    .Y(_007_[4])
  );
  NAND _307_ (
    .A(_047_),
    .B(synth_vco_h[0]),
    .Y(_121_)
  );
  NAND _308_ (
    .A(_049_),
    .B(Vco_high[0]),
    .Y(_122_)
  );
  NAND _309_ (
    .A(_122_),
    .B(_121_),
    .Y(_008_[0])
  );
  NAND _310_ (
    .A(_047_),
    .B(synth_vco_h[1]),
    .Y(_123_)
  );
  NAND _311_ (
    .A(_049_),
    .B(Vco_high[1]),
    .Y(_124_)
  );
  NAND _312_ (
    .A(_124_),
    .B(_123_),
    .Y(_008_[1])
  );
  NAND _313_ (
    .A(_047_),
    .B(synth_vco_h[2]),
    .Y(_126_)
  );
  NAND _314_ (
    .A(_049_),
    .B(Vco_high[2]),
    .Y(_127_)
  );
  NAND _315_ (
    .A(_127_),
    .B(_126_),
    .Y(_008_[2])
  );
  NAND _316_ (
    .A(_047_),
    .B(synth_vco_h[3]),
    .Y(_128_)
  );
  NAND _317_ (
    .A(_049_),
    .B(Vco_high[3]),
    .Y(_129_)
  );
  NAND _318_ (
    .A(_129_),
    .B(_128_),
    .Y(_008_[3])
  );
  NAND _319_ (
    .A(_047_),
    .B(synth_vco_h[4]),
    .Y(_130_)
  );
  NAND _320_ (
    .A(_049_),
    .B(Vco_high[4]),
    .Y(_131_)
  );
  NAND _321_ (
    .A(_131_),
    .B(_130_),
    .Y(_008_[4])
  );
  NAND _322_ (
    .A(_047_),
    .B(synth_vco_l[0]),
    .Y(_132_)
  );
  NAND _323_ (
    .A(_049_),
    .B(Vco_low[0]),
    .Y(_133_)
  );
  NAND _324_ (
    .A(_133_),
    .B(_132_),
    .Y(_009_[0])
  );
  NAND _325_ (
    .A(_047_),
    .B(synth_vco_l[1]),
    .Y(_134_)
  );
  NAND _326_ (
    .A(_049_),
    .B(Vco_low[1]),
    .Y(_135_)
  );
  NAND _327_ (
    .A(_135_),
    .B(_134_),
    .Y(_009_[1])
  );
  NAND _328_ (
    .A(_047_),
    .B(synth_vco_l[2]),
    .Y(_136_)
  );
  NAND _329_ (
    .A(_049_),
    .B(Vco_low[2]),
    .Y(_137_)
  );
  NAND _330_ (
    .A(_137_),
    .B(_136_),
    .Y(_009_[2])
  );
  NAND _331_ (
    .A(_047_),
    .B(synth_vco_l[3]),
    .Y(_138_)
  );
  NAND _332_ (
    .A(_049_),
    .B(Vco_low[3]),
    .Y(_139_)
  );
  NAND _333_ (
    .A(_139_),
    .B(_138_),
    .Y(_009_[3])
  );
  NAND _334_ (
    .A(_047_),
    .B(synth_vco_l[4]),
    .Y(_140_)
  );
  NAND _335_ (
    .A(_049_),
    .B(Vco_low[4]),
    .Y(_141_)
  );
  NAND _336_ (
    .A(_141_),
    .B(_140_),
    .Y(_009_[4])
  );
  NAND _337_ (
    .A(_047_),
    .B(synth_mf_h[0]),
    .Y(_142_)
  );
  NAND _338_ (
    .A(_049_),
    .B(main_fifo_high[0]),
    .Y(_143_)
  );
  NAND _339_ (
    .A(_143_),
    .B(_142_),
    .Y(_004_[0])
  );
  NAND _340_ (
    .A(_047_),
    .B(synth_mf_h[1]),
    .Y(_144_)
  );
  NAND _341_ (
    .A(_049_),
    .B(main_fifo_high[1]),
    .Y(_145_)
  );
  NAND _342_ (
    .A(_145_),
    .B(_144_),
    .Y(_004_[1])
  );
  NAND _343_ (
    .A(_047_),
    .B(synth_mf_h[2]),
    .Y(_146_)
  );
  NAND _344_ (
    .A(_049_),
    .B(main_fifo_high[2]),
    .Y(_147_)
  );
  NAND _345_ (
    .A(_147_),
    .B(_146_),
    .Y(_004_[2])
  );
  NAND _346_ (
    .A(_047_),
    .B(synth_mf_h[3]),
    .Y(_148_)
  );
  NAND _347_ (
    .A(_049_),
    .B(main_fifo_high[3]),
    .Y(_149_)
  );
  NAND _348_ (
    .A(_149_),
    .B(_148_),
    .Y(_004_[3])
  );
  NAND _349_ (
    .A(_047_),
    .B(synth_mf_h[4]),
    .Y(_150_)
  );
  NAND _350_ (
    .A(_049_),
    .B(main_fifo_high[4]),
    .Y(_151_)
  );
  NAND _351_ (
    .A(_151_),
    .B(_150_),
    .Y(_004_[4])
  );
  NOR _352_ (
    .A(errors[4]),
    .B(errors[2]),
    .Y(_152_)
  );
  NOR _353_ (
    .A(_024_),
    .B(errors[3]),
    .Y(_153_)
  );
  NAND _354_ (
    .A(_153_),
    .B(_152_),
    .Y(_154_)
  );
  NAND _355_ (
    .A(_030_),
    .B(_154_),
    .Y(_155_)
  );
  NAND _356_ (
    .A(_155_),
    .B(_046_),
    .Y(_125_)
  );
  DFF _357_ (
    .C(clk),
    .D(_120_),
    .Q(state[0])
  );
  DFF _358_ (
    .C(clk),
    .D(_125_),
    .Q(state[1])
  );
  DFF _359_ (
    .C(clk),
    .D(_156_),
    .Q(state[2])
  );
  DFF _360_ (
    .C(clk),
    .D(_095_),
    .Q(state[3])
  );
  DFF _361_ (
    .C(clk),
    .D(_014_),
    .Q(state[4])
  );
  DFF _362_ (
    .C(clk),
    .D(_005_[0]),
    .Q(synth_mf_l[0])
  );
  DFF _363_ (
    .C(clk),
    .D(_005_[1]),
    .Q(synth_mf_l[1])
  );
  DFF _364_ (
    .C(clk),
    .D(_005_[2]),
    .Q(synth_mf_l[2])
  );
  DFF _365_ (
    .C(clk),
    .D(_005_[3]),
    .Q(synth_mf_l[3])
  );
  DFF _366_ (
    .C(clk),
    .D(_005_[4]),
    .Q(synth_mf_l[4])
  );
  DFF _367_ (
    .C(clk),
    .D(_004_[0]),
    .Q(synth_mf_h[0])
  );
  DFF _368_ (
    .C(clk),
    .D(_004_[1]),
    .Q(synth_mf_h[1])
  );
  DFF _369_ (
    .C(clk),
    .D(_004_[2]),
    .Q(synth_mf_h[2])
  );
  DFF _370_ (
    .C(clk),
    .D(_004_[3]),
    .Q(synth_mf_h[3])
  );
  DFF _371_ (
    .C(clk),
    .D(_004_[4]),
    .Q(synth_mf_h[4])
  );
  DFF _372_ (
    .C(clk),
    .D(_009_[0]),
    .Q(synth_vco_l[0])
  );
  DFF _373_ (
    .C(clk),
    .D(_009_[1]),
    .Q(synth_vco_l[1])
  );
  DFF _374_ (
    .C(clk),
    .D(_009_[2]),
    .Q(synth_vco_l[2])
  );
  DFF _375_ (
    .C(clk),
    .D(_009_[3]),
    .Q(synth_vco_l[3])
  );
  DFF _376_ (
    .C(clk),
    .D(_009_[4]),
    .Q(synth_vco_l[4])
  );
  DFF _377_ (
    .C(clk),
    .D(_008_[0]),
    .Q(synth_vco_h[0])
  );
  DFF _378_ (
    .C(clk),
    .D(_008_[1]),
    .Q(synth_vco_h[1])
  );
  DFF _379_ (
    .C(clk),
    .D(_008_[2]),
    .Q(synth_vco_h[2])
  );
  DFF _380_ (
    .C(clk),
    .D(_008_[3]),
    .Q(synth_vco_h[3])
  );
  DFF _381_ (
    .C(clk),
    .D(_008_[4]),
    .Q(synth_vco_h[4])
  );
  DFF _382_ (
    .C(clk),
    .D(_007_[0]),
    .Q(synth_vc1_l[0])
  );
  DFF _383_ (
    .C(clk),
    .D(_007_[1]),
    .Q(synth_vc1_l[1])
  );
  DFF _384_ (
    .C(clk),
    .D(_007_[2]),
    .Q(synth_vc1_l[2])
  );
  DFF _385_ (
    .C(clk),
    .D(_007_[3]),
    .Q(synth_vc1_l[3])
  );
  DFF _386_ (
    .C(clk),
    .D(_007_[4]),
    .Q(synth_vc1_l[4])
  );
  DFF _387_ (
    .C(clk),
    .D(_006_[0]),
    .Q(synth_vc1_h[0])
  );
  DFF _388_ (
    .C(clk),
    .D(_006_[1]),
    .Q(synth_vc1_h[1])
  );
  DFF _389_ (
    .C(clk),
    .D(_006_[2]),
    .Q(synth_vc1_h[2])
  );
  DFF _390_ (
    .C(clk),
    .D(_006_[3]),
    .Q(synth_vc1_h[3])
  );
  DFF _391_ (
    .C(clk),
    .D(_006_[4]),
    .Q(synth_vc1_h[4])
  );
  DFF _392_ (
    .C(clk),
    .D(_003_[0]),
    .Q(synth_do_l[0])
  );
  DFF _393_ (
    .C(clk),
    .D(_003_[1]),
    .Q(synth_do_l[1])
  );
  DFF _394_ (
    .C(clk),
    .D(_003_[2]),
    .Q(synth_do_l[2])
  );
  DFF _395_ (
    .C(clk),
    .D(_003_[3]),
    .Q(synth_do_l[3])
  );
  DFF _396_ (
    .C(clk),
    .D(_003_[4]),
    .Q(synth_do_l[4])
  );
  DFF _397_ (
    .C(clk),
    .D(_002_[0]),
    .Q(synth_do_h[0])
  );
  DFF _398_ (
    .C(clk),
    .D(_002_[1]),
    .Q(synth_do_h[1])
  );
  DFF _399_ (
    .C(clk),
    .D(_002_[2]),
    .Q(synth_do_h[2])
  );
  DFF _400_ (
    .C(clk),
    .D(_002_[3]),
    .Q(synth_do_h[3])
  );
  DFF _401_ (
    .C(clk),
    .D(_002_[4]),
    .Q(synth_do_h[4])
  );
  DFF _402_ (
    .C(clk),
    .D(_001_[0]),
    .Q(synth_d1_l[0])
  );
  DFF _403_ (
    .C(clk),
    .D(_001_[1]),
    .Q(synth_d1_l[1])
  );
  DFF _404_ (
    .C(clk),
    .D(_001_[2]),
    .Q(synth_d1_l[2])
  );
  DFF _405_ (
    .C(clk),
    .D(_001_[3]),
    .Q(synth_d1_l[3])
  );
  DFF _406_ (
    .C(clk),
    .D(_001_[4]),
    .Q(synth_d1_l[4])
  );
  DFF _407_ (
    .C(clk),
    .D(_000_[0]),
    .Q(synth_d1_h[0])
  );
  DFF _408_ (
    .C(clk),
    .D(_000_[1]),
    .Q(synth_d1_h[1])
  );
  DFF _409_ (
    .C(clk),
    .D(_000_[2]),
    .Q(synth_d1_h[2])
  );
  DFF _410_ (
    .C(clk),
    .D(_000_[3]),
    .Q(synth_d1_h[3])
  );
  DFF _411_ (
    .C(clk),
    .D(_000_[4]),
    .Q(synth_d1_h[4])
  );
endmodule
